# -*- coding: utf-8 -*-
"""product_authenticity_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QtAuKy6RPovjbrNJX79aLAqw37EY4S-

# **Deep learning approach**
"""

# dependencies installation
!pip install ultralytics opencv-python pytesseract

# package update
!sudo apt update
!sudo apt install -y tesseract-ocr

# importing dependencies
import cv2
import pytesseract
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

# ---------- Preprocess for OCR ----------
def preprocess_for_ocr(cropped_img):
    gray = cv2.cvtColor(cropped_img, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (3, 3), 0)
    _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    resized = cv2.resize(thresh, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
    return resized

# Load YOLO model (YOLOv8n pretrained on COCO by default)
model = YOLO("yolov8n.pt")
# OCR config
custom_config = r'--oem 3 --psm 6'

# Load image
image_path = "/content/drive/MyDrive/Colab_Notebooks/objects/whirlpool.jpg"
image = cv2.imread(image_path)

# Display
cv2_imshow(image)

# ---------- Object Detection + OCR ----------
results = model(image_path)
for result in results:
    for box in result.boxes:
        cls = model.names[int(box.cls)]
        conf = float(box.conf)

        if conf > 0.5:
            print(f"\n🔍 Detected object: {cls} (confidence: {conf:.2f})")

            # Crop detected object
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cropped = image[y1:y2, x1:x2]

            # Apply OCR
            processed = preprocess_for_ocr(cropped)
            text = pytesseract.image_to_string(processed, config=custom_config).lower().strip()

            print("📝 OCR Text Detected:\n", text if text else "No readable text found.")

"""# **API approach**"""

# Installation of dependencies
!pip install google-generativeai

# Import necessary dependencies
import google.generativeai as genai
from PIL import Image
import IPython.display as display
import os
from google.colab import userdata

# Configure API key and initialize model
if "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] = userdata.get('api_key')

os.environ['GOOGLE_API_KEY']=userdata.get('api_key')
model = genai.GenerativeModel(model_name="models/gemini-1.5-pro")

# Load image
image_path = "/content/drive/MyDrive/Colab_Notebooks/objects/whirlpool.jpg"
img = Image.open(image_path)
display.display(img)

# Prompt Gemini to analyze objects and text
prompt = """
You are an AI assistant. Analyze the image and list:
1. Detected object.
2. All visible text within the object.
"""

# Make the multimodal call
response = model.generate_content([prompt, img])

# Show the response
print(response.text)

"""# **Transformer based approach**"""

# 📦 Installation of dependencies
!pip install -q transformers timm torchvision accelerate

# ✅ dependencies import
import torch
import torchvision.transforms as T
import cv2
from PIL import Image
import numpy as np
from transformers import DetrImageProcessor, DetrForObjectDetection
from transformers import TrOCRProcessor, VisionEncoderDecoderModel

# ✅ Load DETR for object detection
detr_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
detr_model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")

# ✅ Load TrOCR for text recognition
trocr_processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-stage1")
trocr_model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-base-stage1")

# ✅ Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
detr_model.to(device)
trocr_model.to(device)

# ✅ Load and display image
image_path = "/content/drive/MyDrive/Colab_Notebooks/objects/whirlpool.jpg"
image = Image.open(image_path).convert("RGB")
cv2_imshow(np.array(image))

# ✅ Object detection using DETR
inputs = detr_processor(images=image, return_tensors="pt").to(device)
outputs = detr_model(**inputs)

# Postprocess
target_sizes = torch.tensor([image.size[::-1]], device=device)
results = detr_processor.post_process_object_detection(outputs, threshold=0.9, target_sizes=target_sizes)[0]

# Visual inspection & OCR
for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):
    class_name = detr_model.config.id2label[label.item()]
    score_val = round(score.item(), 3)
    print(f"\n🔍 DETR Detected: {class_name} ({score_val})")

    # Get bounding box
    box = [int(b.item()) for b in box]
    x1, y1, x2, y2 = box

    # Crop and show
    cropped = image.crop((x1, y1, x2, y2))

    # OCR with TrOCR
    inputs_ocr = trocr_processor(images=cropped, return_tensors="pt").to(device)
    with torch.no_grad():
        generated_ids = trocr_model.generate(**inputs_ocr)
        text = trocr_processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()

    print("📝 OCR Text:", text if text else "No text detected.")